### PR TITLE
Breaking templates out of submodule system

### PR DESCRIPTION
**Pull request by jasedit**
This reduces the ability to ensure everything is matched at a single version, but is much easier to manage.

### CODE REVIEW

**Comment by mangusman07** [comment]
this doesn't appear to make a templates/ folder when cloning recursively. perhaps that's the point, but I figured it would make an empty folder similar to papers/

**Comment by jasedit** [comment]
It should - there's a templates/README.md file present in the PR, so templates has to exist for that file to be cloned. Are you cloning from the source of the PR (jasedit/papers_base) and not the destination (trecvt-oss/papers_base)?

**Comment by mangusman07** [comment]
ah. cloning the destination

**Comment by mangusman07** [comment]
I like this (it took my internet forever to finally clone a paper) and I think I only have one question right now:

in bitbucket, we currently have a lot of papers, and will eventually have a lot of templates. Is it possible to have them in "subfolders" such as /trec/templates/template_name or /trec/papers/paper_name/?

**Comment by jasedit** [comment]
Templates would be subfolders in `papers_base/templates`, for instance, I have `papers_base/templates/me2984` and will have `papers_base/templates/trec` containing many other templates once I refactor that folder. I'm assuming that's what you are asking for?

**Comment by mangusman07** [comment]
actually no, more like what you see on https://bitbucket.org/dashboard/overview?section=all where everything is currently listed as /trec/something. I feel that eventually we will have dozens more repos once we have a bunch of new template repos broken out. Is it possible to label the title of each of these repos accordingly?

**Comment by mangusman07** [comment]
i guess in this case /trec/ is our team?

**Comment by jasedit** [comment]
Ah - so the listing on GitHub. There's no way I'm familiar with in which repositories on GitHub can be organized within an organization (trec is the organization on Bitbucket, here it's TRECVT or trecvt-oss). I suppose we could create a new team to store the templates, so templates would exist in some other team, but that means I have to manage an additional team to grant people read/write access for templates.

**Comment by jasedit** [comment]
The best I've done thus far is creating a repository which contains many templates to help minimize the number of repositories (e.g. https://bitbucket.org/trec/paper_templates). But that's the furthest I've gone so far.

**Comment by mangusman07** [comment]
i guess to clarify, in the future if we were to split those out, could we place them separately in bitbucket.org/trec/template/ieee or bitbucket.org/trec/template/jfr or bitbucket.org/trec/paper/knabe_thesis.... the /template/ and /paper/ being a clarification that the given repo is indeed a paper or template

**Comment by mangusman07** [comment]
ah, nevermind i missed the previous comment. youve answered

**Comment by mangusman07** [comment]
i am prepared to merge this PR but require write access to trecvt-oss to do so

**Comment by jasedit** [comment]
Merging this PR means the TRECVT fork is no longer necessary, but people will need to rework their clone configuration to use it. I'll prepare instructions shortly.

**Pull request merged**
